//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class loc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal loc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp2.loc", typeof(loc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string en_allFiles {
            get {
                return ResourceManager.GetString("en_allFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string en_exit {
            get {
                return ResourceManager.GetString("en_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string en_file {
            get {
                return ResourceManager.GetString("en_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string en_info {
            get {
                return ResourceManager.GetString("en_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string en_new {
            get {
                return ResourceManager.GetString("en_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string en_open {
            get {
                return ResourceManager.GetString("en_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string en_save {
            get {
                return ResourceManager.GetString("en_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        internal static string en_symbols {
            get {
                return ResourceManager.GetString("en_symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols count.
        /// </summary>
        internal static string en_symbolsCount {
            get {
                return ResourceManager.GetString("en_symbolsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files.
        /// </summary>
        internal static string en_textFiles {
            get {
                return ResourceManager.GetString("en_textFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        internal static string en_words {
            get {
                return ResourceManager.GetString("en_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words count.
        /// </summary>
        internal static string en_wordsCount {
            get {
                return ResourceManager.GetString("en_wordsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все файлы.
        /// </summary>
        internal static string ru_allFiles {
            get {
                return ResourceManager.GetString("ru_allFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string ru_exit {
            get {
                return ResourceManager.GetString("ru_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        internal static string ru_file {
            get {
                return ResourceManager.GetString("ru_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инфо.
        /// </summary>
        internal static string ru_info {
            get {
                return ResourceManager.GetString("ru_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый.
        /// </summary>
        internal static string ru_new {
            get {
                return ResourceManager.GetString("ru_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        internal static string ru_open {
            get {
                return ResourceManager.GetString("ru_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string ru_save {
            get {
                return ResourceManager.GetString("ru_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Символы.
        /// </summary>
        internal static string ru_symbols {
            get {
                return ResourceManager.GetString("ru_symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество символов.
        /// </summary>
        internal static string ru_symbolsCount {
            get {
                return ResourceManager.GetString("ru_symbolsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текстовые файлы.
        /// </summary>
        internal static string ru_textFiles {
            get {
                return ResourceManager.GetString("ru_textFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слова.
        /// </summary>
        internal static string ru_words {
            get {
                return ResourceManager.GetString("ru_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество слов.
        /// </summary>
        internal static string ru_wordsCount {
            get {
                return ResourceManager.GetString("ru_wordsCount", resourceCulture);
            }
        }
    }
}
